import 'movie_model.dart';

final movies = [
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar2',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar3',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar4',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar5',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar5',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar6',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar7',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar8',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar9',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar10',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar11',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar12',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar13',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar14',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar15',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar16',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar17',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar18',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar19',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar20',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar21',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar22',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar2.jfif',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2022,
    rating: 10,
    image: 'pictures/avatar.jpg',
  ),
  Movie(
    id: 1,
    name: 'Avatar',
    catagory: 'Action/sci-Fi',
    releaseYear: 2012,
    rating: 10,
    image: 'pictures/avatar1.jpg',
  ),
];
